rancher/fleet-e2e

.github/workflows/master-e2e.yaml
Testrun: https://github.com/rancher/fleet-e2e/actions/runs/7724603509/job/21057106620
This PR basically:
* adds /usr/local/bin to PATH
* installs helm-3 (cutting-edge) and git as its dependency
* installs node/npm over action (even tho cypress running in container it needs to install cy plugins which are then mounted into container)
There is still a problem with cypress which is trying to access rancher by using domain concatenated from IP in reverse order but the install part seems to be ok now.
=> Runner dependencies and tweaks

.github/workflows/master-e2e.yaml, .github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, tests/e2e/suite_test.go, tests/scripts/start-cypress-tests
For scheduled jobs we are unable to use `input.<value>` from dispatch block so I extended the `with:` block by hardcoded values.
Initially I used `env:` block but it is also not supported by `uses:` so I used this hardcoded approach for simplicity. We won't know if scheduled runs are using the values until we merge.
More changes:
* cleanup of unneeded values
* bump to latest k8s
Testrun (2.7 manual): https://github.com/rancher/fleet-e2e/actions/runs/7873742581/job/21481808429
=> Hardcoded values for runs scheduled by cron

.github/workflows/master-e2e.yaml, tests/cypress/cypress.config.ts, tests/cypress/package.json, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Implements: https://github.com/rancher/fleet-e2e/issues/44
- Updated Cypress to the latest version as of today: `13.6.4`
- Updated Cypress Docker images to: `cypress/included:cypress-13.6.4-node-20.11.0-chrome-121.0.6167.85-1-ff-120.0-edge-121.0.2277.83-1`
- Added uncaught exceptions to avoid crashes
- Added video flags as by default videos are not passed in this version.
- Removed command `overwrite` which is incompatible with cy 13. This has turned into a significant speed increase (see screenshot)
- [UI-RM_head_2.7 #37](https://github.com/rancher/fleet-e2e/actions/runs/7927306819)
- [UI-RM_head_2.8 #73](https://github.com/rancher/fleet-e2e/actions/runs/7927130411)
- [UI-RM_head_2.9 #66](https://github.com/rancher/fleet-e2e/actions/runs/7927309676)
-
=> Fleet qa/update cypress

.github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, tests/e2e/suite_test.go
When triggering existing head_2.x workflow manually you can specify exact rancher version by:
* `2.8.2`
* `2.8.2-rc3` ... this will append `--version 2.8.2-rc3` and `--devel` to the helm command
* `devel/2.8` ... this will use `--set rancherImageTag=v2.8-head` and `--devel` (the latest helm chart present)
Note: It always use `rancher-latest` https://releases.rancher.com/server-charts/latest helm repo
Note: unfortunately prime is not supported as it uses different URL for the helm repo:
```
https://charts.rancher.com/server-charts/prime
vs
https://releases.rancher.com/server-charts/latest 
```
=> Allow rancher version as `2.8.2[-rc3]` or `devel/2.7`

.github/workflows/master-e2e.yaml
To switch GCP region/zone geographically closer to dockerhub.com, github.com and gitlab.com services, seems they run on US east coast so I picked `us-east4-a`  where no other GCP instances are running.
Testrun: https://github.com/rancher/fleet-e2e/actions/runs/8003631031
It seems it saved 2 minutes in comparison with initial Indian zone. (12.5 min vs 10.5 min)
=> Switch geo zone to US

tests/e2e/install_test.go
At install time of rancher the fleet resources are not even present and the original check is false positive so I removed it together with the implicit 2 min wait after installing Rancher.
The initial fleet check is now done in a new step waiting for `feet-controller` deployment which is only Fleet resource installed even without login to Rancher webUI.
Other Fleet related resources as `gitjob` and `fleet-agent` are installed only after initial login to Rancher over WebUI.
This PR saves ~2minutes of the jobs execution time.
Runs with related output: 
* 2.8-head https://github.com/rancher/fleet-e2e/actions/runs/8046053378/job/21972551727#step:7:93
* 2.7-head https://github.com/rancher/fleet-e2e/actions/runs/8046058140/job/21972563760#step:7:91
=> Move CheckPod for fleet call after deploying rancher

.github/workflows/master-e2e.yaml, .github/workflows/ui-pr_rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.8.yaml
Fixes https://github.com/rancher/fleet-e2e/issues/55
[regular CI run on PR](https://github.com/rancher/fleet-e2e/actions/runs/8052027683/job/21991303825) => no report
[head-v2.7 ](https://github.com/rancher/fleet-e2e/actions/runs/8051547613/job/21989711418) => report exist
[canceled one](https://github.com/rancher/fleet-e2e/actions/runs/8051660974) => report created but deleted
=> Create an extra WF for PR CI runs only and do not push to QASE

.github/workflows/master-e2e.yaml, .github/workflows/ui-pr_rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/plugins/index.ts, tests/scripts/start-cypress-tests
Implementing part 2 from this task (https://github.com/rancher/fleet-e2e/issues/51) of private repo tests via `http` with Bitbucket.
Successful test with step including repo deletion and reinstalling [here](https://github.com/rancher/fleet-e2e/actions/runs/8068457472/job/22041308858). 
After removing this part, I was expecting the test to fail but it [passed](https://github.com/rancher/fleet-e2e/actions/runs/8068592234) also, so even better.
Passed test as well in 2.7 and 2.9 lanes
[UI-RM_head_2.7 #73](https://github.com/rancher/fleet-e2e/actions/runs/8092662730/job/22113808246#step:9:201)
[UI-RM_head_2.9 #92](https://github.com/rancher/fleet-e2e/actions/runs/8092666963)
=> Implementing Bitbucket private repo test

tests/cypress/e2e/unit_tests/first_login_rancher.spec.ts
Implementing: https://github.com/rancher/fleet-e2e/issues/63
- CI https://github.com/rancher/fleet-e2e/actions/runs/8267264159
In ci seemed ok after 40 seconds:
- Local:
It correctly waits up to 5 minutes for state to be active (in the screenshot it waited 2.8 minutes before giving ok to test)
=> Adding check for local cluster to be ready after rancher login

.github/workflows/master-e2e.yaml, tests/e2e/install_test.go, tests/e2e/suite_test.go
Ref. https://github.com/rancher/fleet-e2e/issues/18
Adds initial support for downstream clusters. 
In the end I just used k3d cluster running on the same runner as k3s with rancher.  The import part is using rancher's cattle.io resources only applied by kubectl CLI.
=> Provision and import single k3d cluster

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Implementation of https://github.com/rancher/fleet-e2e/issues/65
- Created delete function for leftovers of Gitrepos either in default or local
- Corrected function that left logs of unwanted info on runners
- Added extra check of the element in the creating repo process to help minimize duplication of repos after clicking `Create` button
- Refactor delete function to include locator of check deleted repo page
- Others refactors
- Added resource check function
- Major refactor on tests for better reading
https://github.com/rancher/fleet-e2e/actions/runs/8328879488/job/22789937537
=> Fleet qa/65 improve deletion and more

tests/scripts/start-cypress-tests
This solves problem with abandoned Cypress processes inside its docker container. It is probably harmless but it might prevent docker container to spawn new processes in more complex scenarios.
Basically `docker run --init` will spawn special PID 1 inside docker which is able to handle terminated process correctly.
Before fix on runner.
There is no sign of defunct processes while using this PR.
=> Get rid of cy zombies processes in docker

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
After bug fix (https://github.com/rancher/fleet/issues/2128), returning original example  checking redis which discovered the original bug.
Added checks for 3 service names on this test.
Working in [2.7-head](https://github.com/rancher/fleet-e2e/actions/runs/8452022057/job/23151582776#step:9:209) as well
=> Adapting fleet-62 test to redis example after bugfix

tests/e2e/install_test.go
Attempt to to resolve following CI issue by using higher port for downstream k3d cluster and its k8s API endpoint exposed over docker.  I see the problem pretty often like in 1 of 10 CI runs.
It should be safe to merge as it shouldn't have any side effect until we implement support in CI for more downstream clusters.
UPDATE:
* k3d k8s API endpoint always exposed on port 64430
* added curl check by reaching this endpoint and expecting 'Unauthorized' string
* waiting for Ready state of k3d nodes and all CRDs
=> Always expose k3d on the same port 64430

.github/workflows/ui-pr_rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, tests/e2e/suite_test.go, tests/go.mod, tests/go.sum
Ref: https://github.com/rancher/fleet-e2e/issues/91
* New `prime` channel introduced via https://github.com/rancher-sandbox/ele-testhelpers/pull/45
* When running CI against `latest/devel/2.7` new staging registries `stgregistry.suse.com/rancher` are used for pulling `rancher:v2.7-head` and `rancher-agent:v2.7-head` images
Also we had to switch back to original way of rancher version selection as there is not only `latest` channel present anymore but also `prime` in addition.
The bumped module now permits to use for example `prime/2.7.12` for released versions. The pre-release testing procedure for prime is not yet clear.
Accepted values for rancher version are:
```
latest/latest
latest/devel/2.x
latest/2.8.3[-rc3]
prime/devel/2.8 (untested)
```
Testruns (FAILURES are releated to …
=> Bump github.com/rancher-sandbox/ele-testhelpers with support

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/support/commands.ts
Adapt ssh keys locator for 2.7 to make ci green (current [failure](https://github.com/rancher/fleet-e2e/actions/runs/8601757348/job/23569757892#step:9:262))
It should be compatible as well with 2.8 and 2.9
=> Adapt ssh locator for rancher 2.7

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/support/commands.ts
Testing if we can speed up test failures a bit by reducing max timeouts
Removing loop on tests Fleet-6 since it is no longer needed.
=> Fleet qa/review implicit waits and other mechanism

.github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml
Adding more details into run-name for dispatched runs only
=> Use inputs in run-name for dispatched runs

.github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml
I did not update `rancher_version` values for scheduled jobs in our workflow files - it was still using `devel/2.x` instead of `latest/devel/2.x` so all scheduled jobs failed tonight.
=> Update rancher_version values for scheduled jobs

.github/workflows/master-e2e.yaml, .github/workflows/ui-pr_rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
- Added retried on flaky tests (examples: [Fleet-77](https://github.com/rancher/fleet-e2e/actions/runs/8716195109/job/23912577022#step:9:360) or [Fleet-98](https://github.com/rancher/fleet-e2e/actions/runs/8716195109/job/23912577022#step:9:276))
- Bumped kubernetes versions for 2.8-head and 2.9-head lanes to `v1.28.8+k3s1`
CI seem to work: [2.8 ](https://github.com/rancher/fleet-e2e/actions/runs/8720713510/job/23922895601#step:9:308), [2.9](https://github.com/rancher/fleet-e2e/actions/runs/8720904626/job/23924465957#step:9:203)
Errors in those lanes are due to flaky tests.
=> Fleet qa/bump k3s versions and add retries

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Fixes [failed](https://github.com/rancher/fleet-e2e/actions/runs/8732280556/job/23959047616#step:9:266) ci tests on 2.7 due to username present in Azure.
Changing: 
```
https://fleetqateam@dev.azure.com/fleetqateam/fleet-qa-examples/_git/fleet-qa-examples
```
to
```
https://dev.azure.com/fleetqateam/fleet-qa-examples/_git/fleet-qa-examples
```
CI on 2.7 [here](https://github.com/rancher/fleet-e2e/actions/runs/8735472306)
=> Updating url for az private repo

.github/workflows/master-e2e.yaml, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Skipping test 107 on Rancher 2.7 due to backport not implemented for it, making ci fail:
https://github.com/rancher/fleet-e2e/actions/runs/8748283153/job/24008094144#step:9:333 
CI in 2.7: https://github.com/rancher/fleet-e2e/actions/runs/8754736455
=> Adding exception to skip test for rancher 2.7

tests/package.json
Bumping `@rancher-ecp-qa/cypress-library` to version `1.1.0`
=> Bumping @rancher-ecp-qa/cypress-library to 1.1.0

.github/workflows/master-e2e.yaml, tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts, tests/e2e/install_test.go, tests/e2e/suite_test.go
Ref. https://github.com/rancher/fleet-e2e/issues/101
This PR is adding support for provisioning multiple k3d downstream clusters. For simplicity the PR has been split to 2 commits, one for infra and another for cypress.
For now deployment of ~two~ three clusters is hardcoded by setting the env variable `DS_CLUSTER_COUNT=3`, but once needed input for setting the number of clusters can be easily added to workflows.
I also had to modify cypress part as the clusters are named differently, changed from `k3d-imported` to `imported-0` ... `imported-X`.
There was a need to modify also `verifyTableRow` command (and their calls) which now accepts for `expectedText2` either string or regexp like `/([1-9]\d*)\/\1/` for matching a string where a sequence of digits (that starts with a non-zero digit) …
=> Support for multiple downstream cluster provisioning

.github/workflows/master-e2e.yaml
This PR will make CI to create a QASE test run containing full rancher version from `rancher_version` variable.
* By default it will keep the test run name as it was before like `UI-RM_head_2.7`.
* when you trigger CI manually by using `rancher_version` input containing full rancher version (not just `2.7-head`) like `latest/2.7.13-rc5` the QASE run will be named `2.7.13-rc5`, the rc/alpha suffix with dash is optional.
Run with the version:
https://github.com/rancher/fleet-e2e/actions/runs/9124386519
https://app.qase.io/run/FLEET/dashboard/493
Run without the version (failed but later):
https://github.com/rancher/fleet-e2e/actions/runs/9124497648
https://app.qase.io/run/FLEET/dashboard/494
=> Use full rancher version in QASE_RUN_NAME

tests/e2e/install_test.go
Instead of waiting for a non-empty string in internal cluster name and registration command we are waiting now for specific substrings.
* internal cluser name should always contain `c-m-`
* registration command should always contain `curl --insecure`
=> Better downsteam cluster registration handling

.github/workflows/master-e2e.yaml
Bumping these Github actions...
`google-github-actions/auth@v1` -> `v2`
`google-github-actions/setup-gcloud@v1` -> `v2`
`actions/setup-go@v3` -> `v5`
... to avoid these warning on ci
=> Bumping gha to avoid annotation warnings

tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Implementation of [FLEET-43](https://app.qase.io/project/FLEET?previewMode=modal&suite=13&tab=&case=43) and [FLEET-44](https://app.qase.io/project/FLEET?previewMode=side&suite=13&tab=&case=44)
- Refactor of `createRoleTemplate` to add specific verbs per resource
- Further refactor of Fleet-5 to be compliant with previous refactor
- Other refactors to ensure test reliability
=> Adding more Rbac standard user tests (43 and 44) with specifc verbs

tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
Implementation of https://app.qase.io/case/FLEET-45
Usecase: User with list and delete can do this actions linked to fleet workspaces but cannot edit
=> Adding rbac qase 45 list and delete std user

tests/cypress/support/commands.ts
Adding enhancements to avoid flakiness on RBAC tests on ci when trying to assign roles to users and and in other scenarios where `open3dotsMenu` function is called
CI in [2.7](https://github.com/rancher/fleet-e2e/actions/runs/9313935455) and [2.9](https://github.com/rancher/fleet-e2e/actions/runs/9313932832/job/25637222494) green
=> Stabilizing flakiness with "Edit Config" for RBAC tests

tests/package.json
Small bump to https://www.npmjs.com/package/cypress-qase-reporter/v/1.4.3
Normal ci 2.8: https://github.com/rancher/fleet-e2e/actions/runs/9317264575
=> Bumping cypress-qase-reporter to 1.4.3

tests/package.json
The newer version is not compatible with go reporter so we need to stick on 1.4.1
=> qase reporter back to 1.4.1

tests/assets/helm-server-with-auth-and-data.yaml, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
* FLEET-64 is testing helmRepoURLRegex matching the helm repo URL via this [fleet.yaml](https://github.com/fleetqa/fleet-qa-examples-public/blob/main/helm-urlregex-repo/fleet.yaml)
* FLEET-65 is testing helmRepoURLRegex matching the full helm chart URL without involving helm repo via this [fleet.yaml](https://github.com/fleetqa/fleet-qa-examples-public/blob/main/helm-urlregex-chart/fleet.yaml)
Both tests are using positive (the regexp matches) and negative (regexp doesn't match) testing. The tests are designed to be working on **local cluster only** and will be executed **only on Rancher:2.9**.
Both cases are using local (deployed on the cluster under test) helm registry and simple helm chart stored there. The needed local helm registry and its resources are deployed by using new …
=> Tests for FLEET-64 and FLEET-65 testing helmRepoURLRegex feature

tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts, tests/cypress/support/commands.ts
Implementation of tests: [Fleet-46](https://app.qase.io/case/FLEET-46), [Fleet-47](https://app.qase.io/case/FLEET-47), [Fleet-48](https://app.qase.io/case/FLEET-48), [Fleet-50](https://app.qase.io/case/FLEET-50)
**Quick summary:**
- Fleet-46: Test "Standard-user" | Custom Role | Fleetworkspaces, Bundles = [ALL] | GitRepos = [List] 
- Fleet-47: Test "Standard-user" | Custom Role | Fleetworkspaces, Bundles = [ALL] | GitRepos = [List, Create] 
- Fleet-48: Test "Standard-user" | Custom Role | Fleetworkspaces, Bundles = [ALL] | GitRepos = [List, Create, Update, Get]
- Fleet-50: Test "Standard-user" | Custom Role | Fleetworkspaces, Bundles = [ALL] | GitRepos = [List, Delete] 
---
- Created `before` hook within `Describe` to add gitrepos to be used in all test cases
- Test implementation. Done …
=> Fleet qa/rbac std users 46 47 48 50

tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts, tests/cypress/support/commands.ts
Done
On last pr, I introduced [here](https://github.com/rancher/fleet-e2e/pull/144/files#diff-75965941f29be613c2bab5bdb432b711b86c52a2567d7f08dcf8aaeef907eb0cR200) a locator pointing to 2nd title to ensure page was loaded on `Continuous Delivery` option. Namely, this one:
```ts
cy.get('div.title').eq(1).should('exist').and('not.be.empty');
```
While the locator (`div.title`) is correct for all 3 versions (2.7,2.8,2.9), in 2.7 there is only 1 repetition of this locator IF the left menu is hidden, while in 2.8 and 2.9 there are 2 (hence the `eq(2)`). 
See on 2.7 2 locators of `div.title` with menu unfolded...
...and only 1 if menu is folded:
This has caused major failures on [last 2.7 ci](https://github.com/rancher/fleet-e2e/actions/runs/9459472790/job/26062224215#step:9:595), making many …
=> Fixing 2.7 ci

tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
From rancher version `v2.7.14-rc3` and `v2.8.5-rc3` the State of user is `Enabled` instead of `Active` in v2.X-head. 
So far we need to support both user states so I introduced regexp support for both text field in `verifyTableRow` function.
=> Regexp support cy.verifyTableRow

tests/cypress/support/commands.ts
Changing assertion on `addFleetGitRepo` with `editConfig === true` to allow forcing update to occur even if git status is not `Active`
=> Changing assertion pr to attempt fix fleet 77

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Fix for v2.9 - `checkGitRepoStatus` and its calls were simplified - we will always check whether gitrepo Resources are present and their numbers match ( `ready / expected Resources Ready` ).
Edit: originally it was using .then() but it was breaking cy retry ability so I had to switch to .should(callback) way and then within the callback I could use jQuery to manipulate the div object and also do the assertion by expect from jQuery. This approach can be probably used here and there and could help us to avoid wait().
=> Always check resources of gitrepo by regexp

tests/cypress/support/commands.ts
Adapting tests to pass rbac in [2.9](https://github.com/rancher/fleet-e2e/actions/runs/9738013264/job/26870958510#step:9:444) after removal of text `enabled|modified`
=> Remove check on active / modified state due to new icon in 2.9

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
**Problem**: Current 2.9 CI is failing for correctDrift test cases (79,80). The reason for failure is ConfigMap is getting deleted but service is not being removed rather it is being re-created. This behavior is observed after GitRepo deletion.
**Solution**: Used individual paths to ConfigMaps and Services so GitRepo will not install both applications simultaneously. Also, their deletion will be performed separately. 
**Changes made in the PR**: Path is added to individual tests, Removed extra indentation.
While investigating this I found problem: Bundle is not getting removed after deleting GitRepo when multiple paths are used. (https://github.com/rancher/fleet/issues/2586)
=> Fix 2.9 tests

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Implements: #163 on test Fleet-62 
On a GitRepo with a path set, I added an extra click on `Edit Yaml` button and asserted text in it prior creating it. 
Attaching video of automation. This can be observed on second 10
[Screencast from 09-07-24 09:38:54.webm](https://github.com/rancher/fleet-e2e/assets/37271841/ee12904e-4d5a-4195-8148-b39c8f93fc6e)
=> Adding health check on Yaml while creating Gitrepo

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
=> Add clusterGroup test automation

tests/cypress/e2e/unit_tests/first_login_rancher.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
At time latest version of Fleet is not found in charts. This can be also achieved by installing it using `Pre-release` version flag and later upgrading the chart from catalog.
- Added new test within `first_login_rancher.spec.ts` where this applies.
- Added `@upgrade` tag on test; so by default it will be skipped unless called with that tag. 
- Added function `allowRancherPreReleaseVersions` to ensure pre-release option is enabled.
- Added refresh on Rancher repository to ensure pre-release selection is reflected
- Added `upgadeFleet` function to upgrade to latest existing version
CI shows `Pending` when tag not called (ie: [here](https://github.com/rancher/fleet-e2e/actions/runs/10042782282/job/27754037197#step:9:216)): 
CI executes the test when tag `@upgrade` is called (ie: …
=> Manual upgrade fleet from pre release version

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
**Problem: Issue: #171 **
* CI 2.7 is failing due to locator issue: `cy.get('[data-testid="side-menu"]').should('have.class', 'menu-open');`
* CI 2.9 is failing to assert Banner message for test Fleet-25. `const bannerMessageToAssert = 'Matches 2 of 3 existing clusters, including "imported-0"'`
**Fixed:**
* Removed the `cy.get('[data-testid="side-menu"]').should('have.class', 'menu-open');`.
* Updated Banner message from string to Regex to fix it.
**Screenshot:**
Below screenshots are taken with 2 different cluster combination to check Regex working.
<details>
<summary><b>Cluster combination: imported-0 and imported-1</b></summary>
</details>
<details>
<summary><b>Cluster combination: imported-2 and imported-1</b></summary>
</details>
=> Fixed 2.7 nav issue and 2.9 banner text with regex

tests/package.json
Bumping https://www.npmjs.com/package/@cypress/grep to current `4.1.0`
Test using grep tag pointing solely to `@login` and `@fleet-62` and working: https://github.com/rancher/fleet-e2e/actions/runs/10716206138/job/29713352923#step:9:326
=> Bumping cypress/grep plugin

tests/assets/disable_polling_reset_2_replicas.sh, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Implementation of disabling test cases 
Fleet-125 -> Checking that with `pause` then `unpause`, the gitrepo is updated with disable `polling=true`
Fleet-126 -> Same as 125 but with `force update`
Added condition to skip git clone if exists already.
CI 2.9 with other p1 test cases passing: https://github.com/rancher/fleet-e2e/actions/runs/10793755252/job/29936477515
=> Automate disabling polling tests 125 and 126

.github/workflows/ui-rm_prime_alpha_rc.yaml, tests/go.mod, tests/go.sum
- Bump latest `ele-helpers` to add `prime-optimus-alpha/2.x.x-alphaX` registry.
- Updated description for PRIME CI Lane.
=> Bump latest ele-helpers

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Test 126 has been flaky lately on ci
After many tries, It never does is locally.
After some previous investigation, my assumption is that there is some caching on the state of the latest test in the final deployment status which is 5 replicas.
Although the previously existing gitrepo is completely deleted (and the deployment associated with it), I believe that the page may contain some cache from the previously existing test.
What I have done to prove this is:
1. Take a screenshot in the moment that the test should have 2 replicas
2. Reload the page
3. Take a second screenshot to see, in case the status remains at 5, if it changes to 2 at this point.
If flakiness is removed, it will probably mean that some type of caching has been applied.
=> Adding screenshots and reload  to investigate flakiness

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Implementation of test Fleet-143 for known-host expected the chip on gitrepos to be in [Error](https://github.com/rancher/fleet-e2e/blob/main/tests/cypress/e2e/unit_tests/p0_fleet.spec.ts#L162C4-L162C46) status after missmatched known-host key was passed. This was verified by using `cy.verifyTableRow(0, 'Error', '0/0');`. This is vallid and working for 2.9 lane but had an error on 2.8 because the error shown is `Git Updating`.
Product has given ok to this last value, so this pr incorporates that value also as valid.
- Passed `cy.verifyTableRow(0, /Error|Git Updating/, '0/0');` to validate also this option.
Local screenshot
[CI in 2.8](https://github.com/rancher/fleet-e2e/actions/runs/11028782849/job/30629875288#step:9:290) green
=> Allowing value 'Git Updating' to be valid also for 2.8 lanes

.github/workflows/master-e2e.yaml
There was about 8000 Managed Secrets on GCP created by various GCP runners which costs money.
* This PR will set Expiration time by `--ttl=18000s` for newly created secrets so they will be auto removed after 5h. Before this change the secrets were not deleted when running with `destroy=false` input. The secrets are useless when gh action is done so it won't have any impact for debug VM runs.
Testrun: https://github.com/rancher/fleet-e2e/actions/runs/11178473152
=> Set expiration time for GCP runner secrets

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Try to fix flaky test [126](https://github.com/rancher/fleet-e2e/actions/runs/11173818148/job/31062528777#step:9:379): `Fleet-126: Test when `disablePolling=true` and forcing update Gitrepo will sync latest changes from Github` . 
The test seem to "hang" after pushing a commit and pressing force update:
I failed to reproduce this manually or automatically but locally, so I suspect somekind of network or ui hanging may be related
Since I have not identified the root cause, I can only guess and propose a workaround, so I did this:
- Set flaky test at first to prevent possible heavy network issue
- Improved screenshot taking on specific repo
- Changed element to verify from gitrepo screen to resource to force somehow changing windows and check if maybe something is cached.
=> Add remediation for flaky test 126 

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Implements: https://github.com/rancher/fleet-e2e/issues/212 | https://app.qase.io/case/FLEET-144
--- 
- Creates normal gitrepo without TLS certificate
- Goes to secrets and verify secret with `reponame-cabundle`does not exist.
--
CI 2.9-head passing: https://github.com/rancher/fleet-e2e/actions/runs/11237975337/job/31241726033?pr=214#step:9:258
Failures displayed unrelated to this issue
Also in 2.8: https://github.com/rancher/fleet-e2e/actions/runs/11238769174/job/31245149823#step:9:294
=> Adding test to check cabundle secret is not created without tls certificate

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Adding retry ability to test to validate if on second try test succeeds.
- Test 126 ALWAYS works locally
- Fails recently frequently solely on CI and on 1st attempt (not always: example [here](https://github.com/rancher/fleet-e2e/actions/runs/11455335699/job/31872807159#step:9:316))
- After some investigation it looks UI
I will keep this on radar to investigate further, but if we want to consider trying if ok on 2nd attempt this can be a way.
=> Adding retry to polling disable 126

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Adding new tests for job deletion detection:
- https://app.qase.io/case/FLEET-146 -> Checks event job deletion log and job is deleted after applying force update
- https://app.qase.io/case/FLEET-147 -> Checks event job deletion log and job is deleted after commit change.
- https://app.qase.io/case/FLEET-148 -> Checks upon faulty job, event job deletion log DOES NOT appear and job STAYS
- https://app.qase.io/case/FLEET-145 -> Refactored after introduction of function `verifyJobDeleted`
=> Adding more job deletion tests

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Improved assertion to avoid problems when `GotNewCommit` message is not first.
Example [here](https://github.com/rancher/fleet-e2e/actions/runs/11511707937/job/32045597724#step:9:301)
=> Enhancing assertion on job deletion faulty case

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Current regex for rancher version will make that new version 2.10 is not executed (example here, where I wanted to run all tests in [this](https://github.com/rancher/fleet-e2e/actions/runs/11511966283/job/32047284771#step:9:294) `2.10.0-alpha3` and some tests like new [Test Fleet job cleanup](https://github.com/rancher/fleet-e2e/actions/runs/11547186580/job/32136699963#step:9:298) were not present.
This pr attempts to workaround this by changing pointing positively to 2.9 by `/\/2\.9/.test(Cypress.env('rancher_version')` to exclude things that are not 2.7 or 2.8.
Results:
| Test | [2.8-head ](https://github.com/rancher/fleet-e2e/actions/runs/11547211639/job/32136758871#step:9:532)| [2.8-pr](https://github.com/rancher/fleet-e2e/actions/runs/11553239393/job/32154030677#step:9:447) | …
=> Update regex on rancher version to ensure 2.10 is executed

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
We did not check properly this: https://github.com/rancher/fleet-e2e/pull/228#issuecomment-2449449555
Adapting tests 61 and 105 for 2.10 meanwhile this bug is resolved: `https://github.com/rancher/dashboard/issues/12444`
CI on [2.10.0-alpha5](https://github.com/rancher/fleet-e2e/actions/runs/11614039752)
=> Adding workaround for error content check on 2.10 for invalid characters

tests/cypress/support/commands.ts
=> Updated locator to fix 2.8 clusterGroup failures

.github/workflows/master-e2e.yaml, tests/package.json
Bumping Cypress to latest 13.16.0
Tests results on different lanes show sporadic  errors on certain tests: 
- [2.8](https://github.com/rancher/fleet-e2e/actions/runs/12356421690) (2 failed tests), 
- [2.9](https://github.com/rancher/fleet-e2e/actions/runs/12356403390/job/34502032064?pr=243) (3 failed tests), 
- [2.10](https://github.com/rancher/fleet-e2e/actions/runs/12356416901/job/34502023894#step:9:602) (1 failed  test)
Perhaps can be merged and see how these tests evolve over next days. Some tweaking including slowing down tests may be considered as well.
=> Bumping Cypress to 13.16.0

.github/workflows/master-e2e.yaml
Bump of node version to avoid [this](https://github.com/rancher/fleet-e2e/actions/runs/12386100844/job/34573447275#step:9:51) warn on ci
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'mocha@11.0.1',
npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
```
CI on `head`: https://github.com/rancher/fleet-e2e/actions/runs/12397332482
=> Bump node to version 18

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Skipping test 126 to to unattended bug.
Test is being skipped in 2.9 while passing in [2.10](https://github.com/rancher/fleet-e2e/actions/runs/12429821035/job/34704071319#step:9:316)
=> Skipping test 126 in 2.9 due to unfixed error

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Fleet-79 test case continuously failing at auto correction of Service Port update when using CorrectDrift.
The issue: https://github.com/rancher/fleet/issues/2609 is not completely fixed instead, this service port update kept as a cornercase for CorrectDrift.(See comment for more detail: https://github.com/rancher/fleet/issues/2609#issuecomment-2504051729)
=> Updated logic of test to pass as it is in 2.9

tests/cypress.config.ts
We are getting ocassionally on ci memory errors related like this one: https://github.com/rancher/fleet-e2e/actions/runs/12740474984/job/35505731067
```
We detected that the Electron Renderer process just crashed.
We have failed the current spec but will continue running the next spec.
This can happen for a number of different reasons.
If you're running lots of tests on a memory intense application.
- Try increasing the CPU/memory on the machine you're running on.
- Try enabling experimentalMemoryManagement in your config file.
- Try lowering numTestsKeptInMemory in your config file during 'cypress open'.
```
To try reduce its incidence we will try to follow the indication and enable flags `experimentalMemoryManagement` and reduce `numTestsKeptInMemory`
Edit: I added other improvements as …
=> Adding flags for memory improvements

.github/workflows/master-e2e.yaml
Noticed [this](https://github.com/rancher/fleet-e2e/actions/runs/12984195058/job/36206685995#step:9:54) issue after recent updates:
```
npm install
+ npm install
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'glob@11.0.1',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.6', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'jackspeak@4.0.2',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.6', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'minimatch@10.0.1',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE …
```
=> Bumping node to 20

tests/cypress.config.ts, tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/support/commands.ts
Done:
- Adjusting locators to be compatible in 2.11. (mainly for jobs clean-up tests)
- Extending wait for hamburger menu due to speed in 2.11
- Removing flag `numTestsKeptInMemory`that caused certain issues.
- Confirmed that setting `Chrome` caused some tests to be flaky (in particular test Fleet-103): https://github.com/rancher/fleet-e2e/actions/runs/12991049858/job/36227693722#step:9:366
=> Fixing CI due to locators and other issues

tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
Test [fleet-156](https://github.com/rancher/fleet-e2e/actions/runs/13024126797/job/36330276499#step:9:507) is not being triggered due to incorrect tag.
=> fixing incorrect tag for test to be triggered on ci

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
=> Automate GitJob security context test

tests/e2e/suite_test.go, tests/e2e/upgrade_test.go
~Fixes: #266~
- In this PR, I have added the QASE ID to the upgrade test.
- This will ensure when we run CI for Upgrade will update the result of upgrade test in the QASE Tool.
- This PR will implement #266
=> Added QASE ID to upgrade test to report QASE Tool

.github/workflows/master-e2e.yaml, .github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_upgrade.yaml
- This PR will add separate artifacts for Cypress runs before and after upgrade.
- This PR will implement: #270
=> Separate artifact for cypress

.github/workflows/master-e2e.yaml, tests/cypress/e2e/unit_tests/upgrade_fleet.spec.ts, tests/cypress/plugins/index.ts, tests/scripts/start-cypress-tests
In this PR below things will be performed:
- Updated `cy.log()` message for upgrade
- Read the Fleet image version before the upgrade
- From all downstream clusters, check the fleet-agent pod image after upgrade only
- This test only run after upgrade only to make sure Fleet is upgraded properly on it's downstream clusters too. 
_**Note: Current CI for PR check is not execute this test.**_
=> Add Sanity check for cluster after upgrade

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
This PR will do:
- Creates GitRepo with `6 resources` on `each cluster.`
- There are `3 clusters` which already had `7 resources` (`ConfigMap, Fleet-agent, secrets etc.`)
- So the total resource count on `each cluster` will be `6+7=13`
- We are getting resource counts from GitRepo and clusters page itself.
Following actions are performed:
- Get the resources from `GitRepo page`.
- Add `7 default resources` to the count.
- Get the `total count of resource` available on `each cluster page`.
- Verify that `GitRepo Resource count` and `EQUAL TO` `Resource count` available on `each clusters page`.
=> Added test for Fleet resource count on cluster

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
- https://github.com/rancher/fleet/pull/3209
- https://github.com/rancher/fleet/issues/3186
- https://github.com/rancher/fleet/pull/3238
- https://github.com/rancher/dashboard/pull/13244
---
- **Total resources GitRepo will install** = Total 18 
- **Default resources already present per cluster** = 6
- **Number of clusters** = 3
1. **Total resources after GitRepo created**:
-  Total 18 resources are created on 3 clusters, i.e. 6 resources each cluster.
2. **Subtract the default resources to find new resources installed**:
- For each cluster:  
New resources installed = 12  (total resources) - 6 (default resources) = 6 (_new resources_)
3. **Verify total installed resources on all clusters with GitRepo installed resources.**:
- Total resources installed across **3 clusters** =  **6 * 3 = …
=> Fix test 155 prevent it for failing

.github/workflows/ui-rm_head_2.11.yaml, tests/cypress/support/commands.ts
- In this PR, it will fix the default head version instead of 2.11
- Also, added constant to include the head version as well as 2.11 version in `addGitRepo` function.
=> New 2.11 lane fix and GitRepo function update

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
Description of what automated:
- New test to apply special flag
- https://app.qase.io/case/FLEET-168
- https://app.qase.io/case/FLEET-169
- https://app.qase.io/case/FLEET-170
- https://app.qase.io/case/FLEET-171 (Skipped for the moment)
- https://app.qase.io/case/FLEET-172
---
- [2.11 #86](https://github.com/rancher/fleet-e2e/actions/runs/14464264647)
- [prime-optimus-alpha/2.10.5-alpha1 #154](https://github.com/rancher/fleet-e2e/actions/runs/14464307781)
- [2.9 #922](https://github.com/rancher/fleet-e2e/actions/runs/14464331319)
=> New  known-host and life cycle features

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
If test 171 is not successfull, hook to restablish known host is not working like [here](https://github.com/rancher/fleet-e2e/actions/runs/14875260608/job/41771294619#step:9:297) in 2.10.
This is a workaround moving the `after` hook at the end of 171 into a `before` hook next test.
It needs to be refined later, but for now it should let 2.10 test cases pass
=> Workaround for known-host-tests

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts
Removing calls to `closePopWindow` after fix of https://github.com/rancher/dashboard/issues/14295
Tested in [prime-optimus-alpha/2.10.6-alpha6](https://github.com/rancher/fleet-e2e/actions/runs/15108876055/job/42463642506) and no traces of pop-up window appeared
=> Removing workaround calls closePopWindow after bug fix

.github/workflows/master-e2e.yaml, .github/workflows/ui-rm_head.yaml
Updating tests on 2.12 to point to specific branch 2.12-stable
Updating Rancher channel to latest/devel/head
Test on head ci pointing to 2.12 stable branch: https://github.com/rancher/fleet-e2e/actions/runs/16003447775/job/45144680364
=> updating branch to use 2.12-stable branch

tests/assets/cluster-group-tests/clusterGroup.yaml, tests/assets/cluster-group-tests/clusterGroupMultipleApps.yaml, tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts
=> Fix clusterGroup 2 failed tests and clusterGroup tests added back for 2.12 via YAML.

.github/workflows/master-e2e.yaml, tests/package.json
Upgraded:
- `"cypress": "^15.2.0"`
- `"cypress-mochawesome-reporter": "^4.0.2",`
- `actions/checkout@v4` -> `actions/checkout@v5`
- `google-github-actions/auth@v2` -> `google-github-actions/auth@v3`
- `google-github-actions/setup-gcloud@v2`-> `google-github-actions/setup-gcloud@v3`
- `actions/checkout@v4` -> `actions/checkout@v5`
- `actions/setup-go@v5` -> `actions/setup-go@v6`
- From 20 to `current` to prevent logs like [this](https://github.com/rancher/fleet-e2e/actions/runs/17975800347/job/51134395782#step:11:61) one with newer versions of mochawesome-reporter:
```
npm install
+ npm install
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'cypress-mochawesome-reporter@4.0.2',
npm warn EBADENGINE   required: { node: '>=22' },
npm warn EBADENGINE   current: { node: …
```
=> Refs/heads/fleet qa/several bumps

tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts
In this PR, test is added to check Fleet's behavior with resources when `doNotDeploy` option is used with values `true` in `fleet.yaml`:
- `doNotDeploy: true`: When set to `true`, `Fleet` skips deploying resources to clusters that match the specified labels in the `targetCustomizations` section.
More information about `doNotDeploy`: https://fleet.rancher.io/ref-fleet-yaml#targeting-and-customization
| `targetCustomizations` Option | Description |
|--------|--------|
| `targetCustomizations.doNotDeploy` | If true, resources will not be deployed to the matched clusters. | 
_See Issue: #393_
=> Added test automation to check `doNotDeploy: true`

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/support/commands.ts
Added automation for FLEET-191
Added automation to check that gitrepo can be deployed in private Github repository using solely pass token without username.
Valid only 2.12.3 onwards
Added prevention to be executed in 2.11
CI on 2.12 [here](https://github.com/rancher/fleet-e2e/actions/runs/18304894030/job/52119878736#step:10:309)
=> Adding test to deploy gitrepo on private gh without username

tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts
Added exclusion for Rancher 2.11 of test [Fleet-190 ](https://app.qase.io/case/FLEET-190)targeting Helmops given that modern UI implementation is in 2.12 onwards and collides with present one.
The test fails because is unable to find HelmOps on UI changes from 2.12 onwards. On top of this, the fix was not backported to 2.11 so there is no point in testing it there.
=> Adding exclusion to test 190 for 2.11
