rancher/fleet-e2e

.github/workflows/master-e2e.yaml
A proper name for runner instances and proper GCP template name.
+ Creation of needed GH_REPO variable copied from turtles
=> GCP template and runner instance names

.gitignore
Implements: https://github.com/rancher/fleet-e2e/issues/9
=> Update paths in `.gitignore`

README.md
This PR will address issue: #13
=> Add status badges to the README file.

.github/workflows/master-e2e.yaml, .github/workflows/ui-rm_head_2.7.yaml, README.md
=> Add CI pipeline for Rancher 2.7-head

.github/workflows/master-e2e.yaml, .github/workflows/ui-rm_head_2.9.yaml
Testing needed envar removed on previous works.
Cron changed as test to see if main run picks it up correctly.
=> testing bringing back needed k8s var.

.github/workflows/master-e2e.yaml, .github/workflows/ui-rm_head_2.9.yaml
=> Revert "testing bringing back needed k8s var."

.github/workflows/master-e2e.yaml, .github/workflows/ui-rm_head_2.9.yaml
=> [REVERT_IF_FAILED] Fixes CI failure

.github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml
Fixes: #36 
This PR will also reverts previously merged PR's.
=> Revert few changes and add new improvments

.github/workflows/master-e2e.yaml, .github/workflows/ui-rm_head_2.9.yaml
=> Re-added environment variables and CI-jobs params

.github/workflows/master-e2e.yaml, .github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml
=> Restoring all changes made by sbulage.

.github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml
Implementation of https://github.com/rancher/fleet-e2e/issues/28
Run tests against all lanes when pushing to main
Ci ok:
- https://github.com/rancher/fleet-e2e/actions/runs/7840555525
- https://github.com/rancher/fleet-e2e/actions/runs/7832246860
- https://github.com/rancher/fleet-e2e/actions/runs/7840554573
=> adding test triggering prior pushing to main

.github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml
After adding `on.push` event we have to extend the condition for `destroy_runner` step.
ref. https://docs.github.com/en/actions/learn-github-actions/expressions#example-matching-an-array-of-strings
=> Fix event types

.github/workflows/master-e2e.yaml, .github/workflows/ui-pr_rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/plugins/index.ts, tests/scripts/start-cypress-tests
Automating part 3 of https://github.com/rancher/fleet-e2e/issues/51
=> Adding Github private repo test

.github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, README.md
Badges don't work as expected.
=> Revert "Use matrix instead of extra workflows"

.github/workflows/master-e2e.yaml, .github/workflows/ui-pr_rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, README.md, tests/cypress/cypress.config.ts, tests/cypress/e2e/unit_tests/first_login_rancher.spec.ts, tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/package.json, tests/cypress/plugins/index.ts, tests/cypress/support/e2e.ts, tests/cypress/tsconfig.json, tests/scripts/start-cypress-tests
Implementation of: https://github.com/rancher/fleet-e2e/issues/70
=> Implementation of cypress/grep

.github/workflows/master-e2e.yaml, .github/workflows/ui-pr_rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/plugins/index.ts, tests/scripts/start-cypress-tests
Implementation of point 4 of https://github.com/rancher/fleet-e2e/issues/51
=> Implementing Azure devops http private repo test

.github/workflows/ui-pr_rm_head_2.8.yaml, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
=> Automate test for 'keepResource' option

.github/workflows/master-e2e.yaml
ref #14 
Adding: 
helm cli version
fleet app version
fleet images on local cluster
=> Fleet version and images in report

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Fixes: #82
Add check application status to:
=> Add check application status to each test

.github/workflows/master-e2e.yaml, .github/workflows/ui-pr_rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.7.yaml, .github/workflows/ui-rm_head_2.8.yaml, .github/workflows/ui-rm_head_2.9.yaml, tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/plugins/index.ts, tests/cypress/support/commands.ts, tests/scripts/start-cypress-tests
Implements: https://github.com/rancher/fleet-e2e/issues/79
=> Fleet qa/79 test ssh private repo

.github/workflows/ui-rm_head_2.9.yaml, tests/go.mod, tests/go.sum
ref. https://github.com/rancher-sandbox/ele-testhelpers/pull/46
=> Bump ele-testhelpers to add support for alpha channel

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
=> Added test for correctDrift

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
=> Added test for existing GitRepo has keepResources

tests/cypress/e2e/unit_tests/first_login_rancher.spec.ts
PR to include qase numbers on login tests
=> Fleet qa/login updates

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
=> Add test no change local cluster to another workspace

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Done:
Added Imagescan test for non-expected semver range (Qase: Fleet-112)
Added necessary commands
Added accesMenuSelection enhancements
Skipped for 2.7 tests as it will fail there due to lack of backport
=> Automation to verify Imagescan does not break fleet controller

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts
Implementing OCI test for basic helm chart support:
Ref: [Fleet-60](https://app.qase.io/project/FLEET?previewMode=side&suite=5&tab=&case=60)
=> Fleet qa/60 oci helm public

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Implementing [QASE FLEET-127](https://app.qase.io/project/FLEET?previewMode=side&suite=5&tab=&case=127)
=> Implementing test for Private OCI helm chart support GHCR

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts
=> Add configmap test for correctDrift

tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
=> Added RBAC FLEET-42 test automation

tests/assets/git-repo-restrictions-allowed-target-ns.yaml, tests/assets/git-repo-restrictions-non-exists-ns.yaml, tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
Fixes: #143 
Added supported gitreporestrictions yaml files.
=> Automated 2 cases of GitRepoRestrictions

tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
=> Automate Fleet-41

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
Fixes: #151 
2.7 CI RUN: https://github.com/rancher/fleet-e2e/actions/runs/9549739159 <--- :green_circle: Passed
=> Fix FLEET-79 flakiness due to residual of resource

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts, tests/cypress/support/commands.ts
Deleting force update everywhere
=> Fleet qa/test force update removal

tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts
=> Fleet qa/rbac userbase fleetworkspaces

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
v2.9 testrun here https://github.com/rancher/fleet-e2e/actions/runs/9710296749 PASSED with one unrelated failure
=> Return gitrepo resources checks for tests in local-fleet namespace

tests/cypress/support/commands.ts
An attempt to save 4x cy.get call within verifyTableRow()
v2.9 run https://github.com/rancher/fleet-e2e/actions/runs/9764811327/job/26954053283
=> Refactoring of verifyTableRow

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
=> Add clusterGroup automation for mulitple application

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
=> Add third cluster to existing clusterGroup

tests/assets/git-repo-multiple-app-cluster-selector.yaml, tests/assets/git-repo-single-app-cluster-selector.yaml, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
=> Add single/multiple app deploy using cluster selector

tests/assets/git-repo-multiple-app-cluster-selector.yaml, tests/assets/git-repo-single-app-cluster-selector.yaml, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
=> Automated test fleet-20 add label to third cluster

.github/workflows/rm-prime_2.8_and_2.9.yaml, .github/workflows/ui-rm_prime_alpha_rc.yaml
=> Added new CI lane for Prime/Alpha build testing

tests/assets/gitrepo-multi-app-cluster-group-selector.yaml, tests/assets/gitrepo-single-app-cluster-group-selector.yaml, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
=> Automate clusterGroupSelector test FLEET 30 and 31

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts
=> Renamed constants and updated label removal

.github/workflows/ui-rm_head_2.7.yaml, README.md
Removing cron job from 2.7 lane given EOL is coming soon (nov 18th)
=> Removing cron job from 2.7 given EOL soon.

tests/assets/git-repo-keep-resources-true.yaml, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts
=> Automate keepResources via GitRepo yaml

.github/workflows/ui-rm_head_2.10.yaml, README.md
Adding new Rancher 2.10 workflow
Updating README label for 2.10
=> New CI test lane for Rancher 2.10

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts
=> Fix Fleet-27 test case failure behavior

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
=> Automated clusterGroupSelector Fleet-32 test

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts
=> Automate clustergroup test cases Fleet-28 and Fleet-29

.github/workflows/ui-rm_head_2.8.yaml
- Change CI 2.8 frequency from daily to weekly.
=> Make CI 2.8 Weekly

.github/workflows/ui-rm_head.yaml, README.md
Adding new  lane for head version on Rancher
=> Adding new testing Rancher head version lane

tests/package.json
Bumping lints to latest version
=> Bump lints

.github/workflows/ui-pr_rm_current.yaml
=> Updating version and name in pr lane

.github/workflows/ui-rm_head.yaml, .github/workflows/ui-rm_head_2.10.yaml, .github/workflows/ui-rm_head_2.9.yaml, .github/workflows/ui-rm_prime_alpha_rc.yaml
=> Updated K8s version to all lanes as per support

tests/package.json
Problem: 
- See this issue: https://github.com/rancher-sandbox/rancher-ecp-qa/issues/21
Solution:
- PR merged, has all screenshots.
- https://github.com/rancher-sandbox/rancher-ecp-qa/pull/22
=> Update rancher-ecp-ca contains logout function fix

tests/package.json
=> Updated rancher-ecp-ca lib

tests/package.json
=> Revert "Updated rancher-ecp-ca lib"

tests/cypress.config.ts, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Fixes: #279 
Local Runs:
| 2.11-head | 2.10-head |
|--------|--------|
| ![Screenshot from 2025-02-20 16-18-00](https://github.com/user-attachments/assets/bdbbee80-82d0-4a7a-8454-69fae84f1dc4) | ![Screenshot from 2025-02-20 16-16-37](https://github.com/user-attachments/assets/7c62e974-3b83-4525-bafb-9754b266d6f2) |
=> Fix Locator: CI head Run

.github/workflows/ui-rm_head_2.11.yaml, .github/workflows/ui-rm_head_2.7.yaml, tests/cypress/support/commands.ts
=> New 2.11 head lane and regex change in addGitRepo function

tests/go.mod, tests/go.sum
<details>
<summary> ele-testhelpers </summary>
</details>
=> Updated test-elehelpers

.github/workflows/ui-pr_rm_current.yaml
=> Updated PR CI lane to 2.11-head

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts
=> Add automation for clusterSelector fleet-19

tests/cypress/e2e/unit_tests/p0_fleet.spec.ts
- During recent failures of Azure tests due to the token is expired, let's skip it for now. Later, back again after token restored.
- Also, changed place of test Fleet-152 above the `job cleanup` tests. which might be cause for failure of it.
=> Disabled Azure tests, shuffled Fleet-152

tests/go.mod, tests/go.sum
=> Updated ele-testhelpers to latest

tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts
=> Extended version check and added timeout to load element

tests/assets/helm-app-test-map-configmap.yaml, tests/cypress/e2e/unit_tests/p1_fleet.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/e2e.ts
Automates: #308 
Do Not Merge until: https://github.com/rancher/fleet-test-data/pull/26
=> Automate helm-app valuesFrom and valuesFiles tests

.github/workflows/ui-rm_head.yaml, .github/workflows/ui-rm_head_2.10.yaml, .github/workflows/ui-rm_head_2.11.yaml
=> Updated cron time and k3s versions

.github/workflows/ui-rm_head_2.9.yaml
=> Using 0 for Sunday instead of 7

.github/workflows/ui-rm_head_2.10.yaml, .github/workflows/ui-rm_head_2.11.yaml, .github/workflows/ui-rm_head_2.12.yaml, README.md
Done:
- Updating new head pointing to 2.13 head
- Created new 2.12 workflow
- Updated cron jobs to avoid collisions among workflows.
=> Fleetqa/add new 2.13 branch

README.md
=> Fixing columns in ReadMe

tests/cypress/e2e/unit_tests/p1_2_fleet.spec.ts, tests/cypress/e2e/unit_tests/rbac_fleet.spec.ts, tests/cypress/support/commands.ts
Daily CI for 2.12 and head are failing with ClusterGroup tests. This PR will fix the test failures.
=> Fix 2.12 head tests

.github/workflows/ui-rm_prime_alpha_rc.yaml
=> Removed default value for branch 2.10-stable
